import path from 'node:path';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    globals: true,
    globalSetup: ['tests/setup/test-artifacts.global-setup.ts'],
    setupFiles: ['tests/setup/test-artifacts.setup.ts'],
    testTimeout: 20_000,
    hookTimeout: 20_000,
    maxWorkers: 4,
    projects: [
      {
        extends: true,
        test: {
          name: 'components',
          environment: 'jsdom',
          setupFiles: ['tests/setup/component-testing.setup.ts'],
          include: ['tests/unit/components/**/*.test.{ts,tsx}'],
        },
      },
      {
        extends: true,
        test: {
          name: 'unit-fast',
          isolate: false,
          include: ['tests/unit/**/*.test.ts'],
          exclude: [
            'tests/unit/channels/message-service-*.test.ts',
            'tests/unit/channels/telegram-*.test.ts',
            'tests/unit/components/**/*.test.{ts,tsx}',
          ],
        },
      },
      {
        extends: true,
        test: {
          name: 'unit-isolated',
          isolate: true,
          include: [
            'tests/unit/channels/message-service-*.test.ts',
            'tests/unit/channels/telegram-*.test.ts',
          ],
        },
      },
      {
        extends: true,
        test: {
          name: 'core-isolated',
          isolate: true,
          include: ['tests/**/*.test.ts'],
          exclude: [
            'tests/unit/**/*.test.ts',
            'tests/e2e/**/*.e2e.test.ts',
            'tests/unit/components/**/*.test.{ts,tsx}',
          ],
        },
      },
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      exclude: [
        'components/**',
        'src/modules/**',
        'app/api/model-hub/**',
        'src/server/model-hub/**',
        'src/server/skills/**',
        'app/api/skills/**',
        'src/server/personas/**',
        'src/server/channels/messages/service.ts',
        'src/server/channels/outbound/router.ts',
        'src/server/channels/pairing/telegramPolling.ts',
        'src/skills/hooks/**',
        'src/server/agent-v2/**',
        'src/server/knowledge/**',
        'src/server/agent-room/services/turnDispatch.service.ts',
        'src/server/agent-room/services/swarmResolution.service.ts',
        'src/server/agent-room/services/turnCompletion.service.ts',
        'src/server/agent-room/services/llmFriction.service.ts',
        'src/server/channels/messages/commands/**',
        'src/server/memory/mem0/sanitization.ts',
        'src/server/memory/mem0/deduplication.ts',
        'src/server/master/execution/**',
        'src/server/channels/telegram/voice.ts',
        'src/server/proactive/sqliteProactiveRepository.ts',
        'src/server/channels/messages/service/transcriptRepair.ts',
        'src/server/channels/messages/service/subagent/**',
        'src/server/master/systemOps.ts',
        'src/server/master/metrics.ts',
        'src/server/channels/pairing/unpair.ts',
        'src/lib/planning-utils.ts',
        'src/server/channels/messages/service/commands/**',
        'src/server/channels/outbound/slack.ts',
        'src/server/channels/messages/service/recall/evidence/format.ts',
        'src/server/gateway/methods/agent-v2/registerSessionMethods.ts',
        'app/api/clawhub/search/route.ts',
        'app/api/agents/**',
        'app/api/workspaces/**',
        'app/api/master/notes/route.ts',
        'app/api/master/reminders/route.ts',
        'app/api/master/runs/**',
        'app/api/automations/**',
        'app/api/tasks/**',
        'src/lib/debug.ts',
        'src/lib/openclaw/client.ts',
        'app/api/webhooks/agent-completion/route.ts',
        'app/api/channels/whatsapp/accounts/route.ts',
        'src/shared/normalizeArgs.ts',
        'src/server/agent-room/prompt/turnPrompt.builder.ts',
        'src/server/tasks/testing/**',
        'src/shared/domain/swarmPhases.ts',
        'src/server/master/cronBridge.ts',
        'src/server/channels/messages/service/recall/search/strict.ts',
        'src/server/telegram/personaTelegramPoller.ts',
        'src/auth.ts',
        'src/server/memory/operations/**',
        'src/server/master/capabilities/understandingLoop.ts',
        'src/server/tasks/dispatch/prepareDispatch.ts',
        'src/server/tasks/taskHydration.ts',
        'app/api/channels/conversations/route.ts',
        'app/api/channels/messages/route.ts',
        'app/api/clawhub/**',
        'src/commands/health/checks/coreChecks.ts',
        'src/server/memory/utils/scoring.ts',
        'src/server/channels/outbound/discord.ts',
        'app/api/openclaw/models/route.ts',
        'src/server/channels/telegram/nativeCommands.ts',
        'src/server/channels/messages/service/toolLoopDetector.ts',
        'src/server/gateway/methods/chat.ts',
        'src/server/automation/flowCompiler.ts',
        'src/server/channels/pairing/slack.ts',
        'src/server/channels/pairing/telegram.ts',
        'app/api/channels/telegram/webhook/route.ts',
        'src/server/channels/webhookAuth.ts',
        'app/api/personas/**',
        'src/server/channels/messages/service/projectGuard.ts',
        'src/server/channels/telegram/media.ts',
        'src/server/channels/telegram/modelSelection.ts',
        'src/server/clawhub/clawhubPromptBuilder.ts',
        'src/server/telegram/personaTelegramPairing.ts',
        'app/api/channels/whatsapp/webhook/route.ts',
        'src/server/tasks/dispatch/failure.ts',
        'src/server/auth/userStore.ts',
        'tests/**',
        '**/*.test.{ts,tsx}',
        '**/*.spec.{ts,tsx}',
      ],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 70,
        statements: 70,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
});
