import type { ProviderCatalogEntry } from './types';

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: 'gemini',
    name: 'Google Gemini',
    icon: 'G',
    authMethods: ['api_key'],
    endpointType: 'gemini-native',
    capabilities: ['chat', 'tools', 'vision', 'audio', 'embeddings'],
    defaultModels: ['gemini-2.5-flash', 'gemini-2.5-pro'],
    docsUrl: 'https://ai.google.dev/gemini-api/docs',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: 'O',
    authMethods: ['api_key', 'oauth'],
    endpointType: 'openai-native',
    capabilities: ['chat', 'tools', 'vision', 'audio', 'embeddings'],
    defaultModels: ['gpt-4.1', 'gpt-4.1-mini', 'o4-mini'],
    apiBaseUrl: 'https://api.openai.com/v1',
    docsUrl: 'https://platform.openai.com/docs/api-reference',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: 'A',
    authMethods: ['api_key'],
    endpointType: 'anthropic-native',
    capabilities: ['chat', 'tools', 'vision'],
    defaultModels: ['claude-sonnet-4-5', 'claude-3-7-sonnet-latest'],
    apiBaseUrl: 'https://api.anthropic.com/v1',
    docsUrl: 'https://docs.anthropic.com/en/api/messages',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: 'R',
    authMethods: ['api_key', 'oauth'],
    endpointType: 'openai-compatible',
    capabilities: ['chat', 'tools', 'vision'],
    defaultModels: ['openai/gpt-4.1-mini', 'anthropic/claude-3.7-sonnet'],
    apiBaseUrl: 'https://openrouter.ai/api/v1',
    docsUrl: 'https://openrouter.ai/docs/quickstart',
  },
  {
    id: 'xai',
    name: 'xAI',
    icon: 'X',
    authMethods: ['api_key'],
    endpointType: 'xai-native',
    capabilities: ['chat', 'tools'],
    defaultModels: ['grok-4', 'grok-3'],
    apiBaseUrl: 'https://api.x.ai/v1',
    docsUrl: 'https://docs.x.ai/docs/overview',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    icon: 'M',
    authMethods: ['api_key'],
    endpointType: 'mistral-native',
    capabilities: ['chat', 'tools', 'embeddings'],
    defaultModels: ['mistral-large-latest', 'ministral-8b-latest'],
    apiBaseUrl: 'https://api.mistral.ai/v1',
    docsUrl: 'https://docs.mistral.ai',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    icon: 'C',
    authMethods: ['api_key'],
    endpointType: 'cohere-native',
    capabilities: ['chat', 'tools', 'embeddings'],
    defaultModels: ['command-a-03-2025', 'command-r-plus'],
    apiBaseUrl: 'https://api.cohere.com/v2',
    docsUrl: 'https://docs.cohere.com',
  },
  {
    id: 'zai',
    name: 'Z.AI',
    icon: 'Z',
    authMethods: ['api_key'],
    endpointType: 'openai-compatible',
    capabilities: ['chat', 'tools', 'vision'],
    defaultModels: ['glm-4.5', 'glm-4.5-air'],
    apiBaseUrl: 'https://api.z.ai/api/paas/v4',
    docsUrl: 'https://docs.z.ai',
  },
  {
    id: 'kimi',
    name: 'Kimi (Moonshot)',
    icon: 'K',
    authMethods: ['api_key'],
    endpointType: 'openai-compatible',
    capabilities: ['chat', 'tools'],
    defaultModels: ['moonshot-v1-8k', 'moonshot-v1-32k'],
    apiBaseUrl: 'https://api.moonshot.cn/v1',
    docsUrl: 'https://platform.moonshot.cn/docs/guide/start-using-kimi-api',
  },
  {
    id: 'bytedance',
    name: 'ByteDance ModelArk',
    icon: 'B',
    authMethods: ['api_key'],
    endpointType: 'openai-compatible',
    capabilities: ['chat', 'tools'],
    defaultModels: ['doubao-1-5-lite-32k-250115', 'doubao-1-5-pro-32k-250115'],
    apiBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    docsUrl: 'https://docs.byteplus.com/id/docs/ModelArk/Authentication',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot / Models',
    icon: 'GH',
    authMethods: ['oauth', 'api_key'],
    endpointType: 'github-native',
    capabilities: ['chat', 'code_pairing'],
    defaultModels: [],
    apiBaseUrl: 'https://api.github.com',
    docsUrl: 'https://docs.github.com/en/rest/models',
  },
];
