import { CommandPermission } from '@/shared/domain/types';

// INITIAL_SKILLS removed — skills are now loaded from SQLite via GET /api/skills

export const SECURITY_RULES: CommandPermission[] = [
  {
    id: 'c1',
    command: 'ls',
    description: 'List directory contents',
    category: 'Files',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c2',
    command: 'pwd',
    description: 'Print working directory',
    category: 'Files',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c3',
    command: 'cd',
    description: 'Change current directory',
    category: 'Files',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c4',
    command: 'rg',
    description: 'Fast text/file search',
    category: 'Files',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c5',
    command: 'cat',
    description: 'Read file contents',
    category: 'Files',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c6',
    command: 'mkdir',
    description: 'Create new directories',
    category: 'Files',
    risk: 'Medium',
    enabled: true,
  },
  {
    id: 'c7',
    command: 'cp',
    description: 'Copy files and folders',
    category: 'Files',
    risk: 'Medium',
    enabled: true,
  },
  {
    id: 'c8',
    command: 'mv',
    description: 'Move or rename files and folders',
    category: 'Files',
    risk: 'Medium',
    enabled: true,
  },
  {
    id: 'c9',
    command: 'git status',
    description: 'Inspect repository state',
    category: 'DevOps',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c10',
    command: 'git diff',
    description: 'Inspect changed code',
    category: 'DevOps',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c11',
    command: 'git log',
    description: 'Inspect commit history',
    category: 'DevOps',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c12',
    command: 'npm install',
    description: 'Install package dependencies',
    category: 'DevOps',
    risk: 'Medium',
    enabled: true,
  },
  {
    id: 'c13',
    command: 'pnpm install',
    description: 'Install package dependencies (pnpm)',
    category: 'DevOps',
    risk: 'Medium',
    enabled: true,
  },
  {
    id: 'c14',
    command: 'npm test',
    description: 'Run test suite',
    category: 'DevOps',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c15',
    command: 'pnpm test',
    description: 'Run test suite (pnpm)',
    category: 'DevOps',
    risk: 'Low',
    enabled: true,
  },
  {
    id: 'c16',
    command: 'curl',
    description: 'Transfer data from/to a server',
    category: 'Network',
    risk: 'Medium',
    enabled: false,
  },
  {
    id: 'c17',
    command: 'Invoke-WebRequest',
    description: 'PowerShell web request',
    category: 'Network',
    risk: 'Medium',
    enabled: false,
  },
  {
    id: 'c18',
    command: 'rm -rf',
    description: 'Recursive deletion (Danger)',
    category: 'System',
    risk: 'High',
    enabled: false,
  },
  {
    id: 'c19',
    command: 'del /f /s /q',
    description: 'Forced recursive deletion (Windows)',
    category: 'System',
    risk: 'High',
    enabled: false,
  },
  {
    id: 'c20',
    command: 'format',
    description: 'Format storage volumes',
    category: 'System',
    risk: 'High',
    enabled: false,
  },
  {
    id: 'c21',
    command: 'shutdown',
    description: 'Shutdown or restart host',
    category: 'System',
    risk: 'High',
    enabled: false,
  },
  {
    id: 'c22',
    command: 'powershell -enc',
    description: 'Execute base64 encoded PowerShell commands',
    category: 'System',
    risk: 'High',
    enabled: false,
  },
  {
    id: 'c23',
    command: 'reg delete',
    description: 'Delete Windows registry keys',
    category: 'System',
    risk: 'High',
    enabled: false,
  },
  {
    id: 'c24',
    command: 'sc stop',
    description: 'Stop Windows services',
    category: 'System',
    risk: 'High',
    enabled: false,
  },
];
